# Generated by Django 3.0.14 on 2024-12-24 23:29

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_tags"),
    ]

    operations = [TrigramExtension()]
